#------------------------------------------------------------
# Values for this lesson.
#------------------------------------------------------------

# Which carpentry is this (swc, dc, lc, or cp)?
# swc: Software Carpentry
# dc: Data Carpentry
# lc: Library Carpentry
# cp: Carpentries (to use for instructor traning for instance)
carpentry: 'dc'

# Overall title for pages.
title: 'Data Analysis and Visualisation in R for Ecologists'

# Life cycle stage of the lesson
# possible values: pre-alpha, alpha, beta, stable
life_cycle: 'stable'

# License of the lesson
license: 'CC-BY 4.0'

# Link to the source repository for this lesson
source: 'https://github.com/fishtree-attempt/R-ecology-lesson/'

# Default branch of your lesson
branch: 'main'

# Who to contact if there are any issues
contact: 'zkamvar@carpentries.org'

# Navigation ------------------------------------------------
# The menu bar will be in the following order:
# 
# - Code of Conduct      (CODE_OF_CONDUCT.md)
# - Setup                (setup.md)
# - Episodes             (episodes/)
# - Learner Resources    (learners/)
# - Instructor Resources (instructors/)
# - Learner Profiles     (profiles/)
# - License              (LICENSE.md)
# 
# Use the following menu items to specify the order of
# individual pages in each dropdown section

# Order of episodes in your lesson 
episodes: 
- 00-before-we-start.Rmd
- 01-intro-to-r.Rmd
- 02-starting-with-data.Rmd
- 03-dplyr.Rmd
- 04-visualization-ggplot2.Rmd
- 05-r-and-databases.Rmd
- 06-pyramid-example.Rmd

# Information for Learners
learners: 
- reference.md

# Information for Instructors
instructors: 
- instructor-notes.md

# Learner Profiles
profiles: 

